# code the pipeline 

name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Clean & transform dataset
      run: python preprocessing.py
    - uses: actions/upload-artifact@v4
      with:
        name: csv
        path: data/*.csv
        retention-days: 1

  train:
    needs: preprocessing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - uses: actions/download-artifact@v4
      with:
        name: csv
        path: data
    - name: Train and save pipeline
      run: python train_model.py
    - uses: actions/upload-artifact@v4
      with:
        name: train-model
        path: models/*.pkl
        retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - uses: actions/download-artifact@v4
      with:
        name: train-model
        path: models
    - uses: actions/download-artifact@v4
      with:
        name: csv
        path: data
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with pytest
      run: pytest